name: native_json_api
description: "native_json_api package project"
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2

dependencies:
  output: ^1.0.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
